using System;
using System.Collections.Generic;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.Xml.Schema;


namespace IAT.Core.Serializable;

[XmlType("IATReport")]
public class IATReport : IWebSocketMessage
{
    [XmlElement("ProductKey", Form = XmlSchemaForm.Unqualified)] public string ProductKey { get; set; } = string.Empty;
    /// <summary>Gets or sets the name of the IAT (Interactive Activation Transaction) being reported.</summary>
    [XmlElement("TestName", Form = XmlSchemaForm.Unqualified)] public string Name { get; set; } = string.Empty;

    /// <summary>Gets or sets the URL associated with the IAT report. This URL may point to additional information or resources related to the IAT.</summary>
    [XmlElement("URL", Form = XmlSchemaForm.Unqualified)] public string URL { get; set; } = string.Empty;

    /// <summary>Gets or sets the number of times the IAT has been administered.</summary>
    [XmlElement("NumAdministrations", Form = XmlSchemaForm.Unqualified)] public int NumAdministrations { get; set; } = 0;

    /// <summary>Gets or sets the number of result sets generated by the IAT.</summary>
    [XmlElement("NumResultSets", Form = XmlSchemaForm.Unqualified)] public int NumResultSets { get; set; } = 0;

    /// <summary>Gets or sets the size of the IAT test in kilobytes (KB). This property indicates the amount of disk space occupied by the test data.</summary>
    [XmlElement("TestSizeKB", Form = XmlSchemaForm.Unqualified)] public int TestSizeKB { get; set; } = 0;

    /// <summary>Gets or sets the date/time the test was uploaded (deployed) to the server.</summary>
    [XmlElement("UploadTimestamp", Form = XmlSchemaForm.Unqualified)] public string UploadTimestamp { get; set; } = string.Empty;

    /// <summary>Gets or sets the date and time when the last data retrieval for the IAT report occurred.</summary>
    [XmlElement("LastDataRetrieval", Form = XmlSchemaForm.Unqualified)] public string LastDataRetrieval { get; set; } = string.Empty;

    /// <summary>Gets or sets the title of the author associated with the IAT report.</summary>
    [XmlElement("AuthorName", Form = XmlSchemaForm.Unqualified)] public string AuthorName { get; set; } = string.Empty;
    /// <summary>Gets or sets the test version.</summary>
    [XmlElement("TestVersion", Form = XmlSchemaForm.Unqualified)] public string TestVersion { get; set; } = string.Empty;
}


[XmlRoot("ServerReport")]
public class ServerReport
{
    /// <summary>Gets or sets the client's first name.</summary>
    [XmlElement("ContactFName", Form = XmlSchemaForm.Unqualified)] public string ContactFName { get; set; } = string.Empty;

    /// <summary>Gets or sets the client's last name.</summary>
    [XmlElement("ContactLName", Form = XmlSchemaForm.Unqualified)] public string ContactLName { get; set; } = string.Empty;

    /// <summary>Gets or sets the client's organization.</summary>
    [XmlElement("Organization", Form = XmlSchemaForm.Unqualified)] public string Organization { get; set; } = string.Empty;

    /// <summary>Gets or sets the  number of IATs alotted.</summary>
    [XmlElement("NumIATsAlotted", Form = XmlSchemaForm.Unqualified)] public int NumIATsAllotted { get; set; } = 0;

    /// <summary>Gets or sets the total number of administrations across IATs.</summary>
    [XmlElement("NumAdministrations", Form = XmlSchemaForm.Unqualified)] public int NumIATsUsed { get; set; } = 0;

    /// <summary>
    /// Gets or sets the number of administrations the  client has remaining.</summary>
    [XmlElement("NumAdministrationsRemaining", Form = XmlSchemaForm.Unqualified)] public int NumAdministrations { get; set; } = 0;

    /// <summary>Gets or sets the disk alottment in MB.</summary>
    [XmlElement("DiskAlottmentMB", Form = XmlSchemaForm.Unqualified)] public int DiskAlottmentMB { get; set; } = 0;

    /// <summary>Gets or sets the remaining disk alottment in KB.</summary>
    [XmlElement("DiskAlottmentRemainingKB", Form = XmlSchemaForm.Unqualified)] public int DiskAlottmentRemainingKB { get; set; } = 0;

    /// <summary>Gets or set the IATReport list.</summary>
    [XmlElement("IATReport", Form = XmlSchemaForm.Unqualified)]
    public List<IATReport> IATReport { get; set; } = new();
}
