//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1240.0 using the following command:
// xscgen --namespace Models.Generated --output . Models\Schemas\Models.xsd --separateFiles
namespace Models.Generated
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1240.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AlternationGroup", Namespace="http://tempuri.org/XMLSchema1.xsd")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlternationGroup
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("URI")]
        public string Uri { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<int> _groupIds;
        
        [System.Xml.Serialization.XmlElementAttribute("GroupIds")]
        public System.Collections.ObjectModel.Collection<int> GroupIds
        {
            get
            {
                return _groupIds;
            }
            private set
            {
                _groupIds = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the GroupIds collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GroupIdsSpecified
        {
            get
            {
                return (this.GroupIds.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AlternationGroup" /> class.</para>
        /// </summary>
        public AlternationGroup()
        {
            this._groupIds = new System.Collections.ObjectModel.Collection<int>();
            this._groupMemberRelIds = new System.Collections.ObjectModel.Collection<string>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _groupMemberRelIds;
        
        [System.Xml.Serialization.XmlElementAttribute("GroupMemberRelIds")]
        public System.Collections.ObjectModel.Collection<string> GroupMemberRelIds
        {
            get
            {
                return _groupMemberRelIds;
            }
            private set
            {
                _groupMemberRelIds = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the GroupMemberRelIds collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GroupMemberRelIdsSpecified
        {
            get
            {
                return (this.GroupMemberRelIds.Count != 0);
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("GroupID")]
        public int GroupId { get; set; }
    }
}
