<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
	  <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Templates\**" />
    <EmbeddedResource Remove="Templates\**" />
    <None Remove="Templates\**" />
    <Page Remove="Templates\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IAT.Core\IAT.Core.csproj">
      <Private>True</Private>
    </ProjectReference>
    <ProjectReference Include="..\IAT.ViewModels\IAT.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\" />
	  <Folder Include="Converters\" />
  </ItemGroup>

</Project>
